### ISSUE TITLE
TypeError: Property 'next' of object #<Context> is not a function

### ISSUE THREAD

**Issue by hamsterready** [geddy/geddy-passport#19]
Using geddy v0.11.8.

Generated new app and run geddy auth. Updated secrets with twitter keys. Started the app.

Accessed http://localhost:4000/login and followed up to http://localhost:4000/auth/twitter

Receiving:

```
TypeError: Property 'next' of object #<Context> is not a function
at Context.actions.error (/home/hamster/tmp/x/node_modules/passport/lib/passport/context/http/actions.js:91:8)
at /home/hamster/tmp/x/node_modules/passport-twitter/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:196:30
at /home/hamster/tmp/x/node_modules/passport-twitter/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:518:17
at passBackControl (/home/hamster/tmp/x/node_modules/passport-twitter/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:374:13)
at IncomingMessage.<anonymous> (/home/hamster/tmp/x/node_modules/passport-twitter/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:386:9)
at IncomingMessage.EventEmitter.emit (events.js:117:20)
at _stream_readable.js:920:16
at process._tickDomainCallback (node.js:459:13)
```

Am I doing something wrong?

I tried with twitter only (removed others from secrets.json) and commented out 

```
var SUPPORTED_SERVICES = [
  'twitter'
//, 'facebook'
//, 'yammer'
];
```

but still no luck.

**Comment by Preetam007** [comment]
try this - http://stackoverflow.com/questions/16337395/passportjs-error-callback-throwing-exception
