### ISSUE TITLE
TypeError: Cannot call method 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by lugaru90** [geddy/geddy-passport#20]
Hey guys,
followed the Tutorial for auth. Then i created a new Local user -> works.
Login in to this local user -> works.
Logging in with facebook -> works.
Tessting again to Login with the Local user returns the following error:

Error: 500 Internal Server Error
TypeError: Cannot call method 'toLowerCase' of undefined
    at eval (eval at <anonymous> (/usr/lib/node_modules/geddy/node_modules/model/lib/adapters/memory/index.js:85:16), <anonymous>:2:28)
    at utils.mixin.load (/usr/lib/node_modules/geddy/node_modules/model/lib/adapters/memory/index.js:110:13)
    at Object.obj.all (/usr/lib/node_modules/geddy/node_modules/model/lib/index.js:391:25)
    at Function.obj.first (/usr/lib/node_modules/geddy/node_modules/model/lib/index.js:348:18)
    at actions.local (/var/www/geddy/leben/app/helpers/passport/actions.js:105:22)
    at callback (/usr/lib/node_modules/geddy/lib/controller/base_controller.js:282:22)
    at controller.BaseController._handleAction (/usr/lib/node_modules/geddy/lib/controller/base_controller.js:295:7)
    at cb [as callback](/usr/lib/node_modules/geddy/lib/app/index.js:258:36)
    at async.Initializer.complete (/usr/lib/node_modules/geddy/node_modules/utilities/lib/async.js:286:10)
    at /usr/lib/node_modules/geddy/lib/app/index.js:269:21

**Comment by johnjelinek** [comment]
:point_up_2: not an ok solution.
